import 'dart:io';

import 'package:path/path.dart' as p;

/// Scans an assets directory and generates a typed Dart source file
/// with [Assets] class providing compile-time safe asset path constants.
///
/// Used by both [SiteGenerator] (on every build) and [ProjectGenerator]
/// (during init) to keep `assets/assets.dart` in sync with the filesystem.
class AssetPathGenerator {
  AssetPathGenerator._();

  /// Scan [assetsDir] and return the generated Dart source for `assets.dart`.
  ///
  /// If [assetsDir] does not exist or is empty, returns a minimal file
  /// with an empty [Assets] class.
  static String generate(String assetsDir) {
    final dir = Directory(assetsDir);
    if (!dir.existsSync()) return _emptyAssets();

    final root = _scanDirectory(dir, 'assets');
    if (root.dirs.isEmpty && root.files.isEmpty) return _emptyAssets();

    return _generateCode(root);
  }

  // ---------------------------------------------------------------------------
  // Scanning
  // ---------------------------------------------------------------------------

  static _AssetDir _scanDirectory(Directory dir, String webPath) {
    final dirs = <_AssetDir>[];
    final files = <_AssetFile>[];

    final entities = dir.listSync()..sort((a, b) => a.path.compareTo(b.path));

    for (final entity in entities) {
      final name = p.basename(entity.path);

      // Skip hidden files/dirs and the generated assets.dart itself.
      if (name.startsWith('.') || name == 'assets.dart') continue;

      if (entity is File) {
        files.add(
          _AssetFile(
            name: name,
            identifier: _toIdentifier(name),
            webPath: '/$webPath/$name',
          ),
        );
      } else if (entity is Directory) {
        final child = _scanDirectory(entity, '$webPath/$name');
        // Skip empty directories.
        if (child.dirs.isNotEmpty || child.files.isNotEmpty) {
          dirs.add(child);
        }
      }
    }

    return _AssetDir(
      name: p.basename(dir.path),
      identifier: _toIdentifier(p.basename(dir.path)),
      webPath: webPath,
      dirs: dirs,
      files: files,
    );
  }

  // ---------------------------------------------------------------------------
  // Code generation
  // ---------------------------------------------------------------------------

  static String _generateCode(_AssetDir root) {
    final buffer = StringBuffer();
    buffer.writeln('// AUTO-GENERATED by DocuDart from the assets/ directory.');
    buffer.writeln('// This file is regenerated on every build. Do not edit.');
    buffer.writeln();
    buffer.writeln('// ignore_for_file: non_constant_identifier_names');
    buffer.writeln();

    // Generate the top-level Assets class first for readability.
    buffer.writeln(
      '/// Type-safe asset paths generated from the `assets/` directory.',
    );
    buffer.writeln('///');
    buffer.writeln('/// Usage:');
    buffer.writeln('/// ```dart');
    buffer.writeln('/// img(src: Assets.logo.logo_webp, alt: \'Logo\')');
    buffer.writeln('/// ```');
    buffer.writeln('abstract class Assets {');
    buffer.writeln('  Assets._();');

    // Root-level files as static final fields.
    for (final file in root.files) {
      buffer.writeln();
      buffer.writeln("  /// `${file.webPath}`");
      buffer.writeln(
        "  static const String ${file.identifier} = '${file.webPath}';",
      );
    }

    // Subdirectories as static const instances.
    for (final dir in root.dirs) {
      final className = _className('Assets', dir.name);
      buffer.writeln();
      buffer.writeln('  static const ${dir.identifier} = $className();');
    }

    buffer.writeln('}');
    buffer.writeln();

    // Generate private classes for each subdirectory (depth-first).
    _generateDirClasses(buffer, root.dirs, 'Assets');

    return buffer.toString();
  }

  /// Recursively generate private `_Assets*` classes for each subdirectory.
  static void _generateDirClasses(
    StringBuffer buffer,
    List<_AssetDir> dirs,
    String parentClassName,
  ) {
    for (final dir in dirs) {
      final className = _className(parentClassName, dir.name);

      // Recurse first so nested classes are defined before they are referenced.
      _generateDirClasses(buffer, dir.dirs, className);

      buffer.writeln('/// Asset paths for `${dir.webPath}/`.');
      buffer.writeln('class $className {');
      buffer.writeln('  const $className();');

      // Files in this directory.
      for (final file in dir.files) {
        buffer.writeln();
        buffer.writeln("  /// `${file.webPath}`");
        buffer.writeln(
          "  final String ${file.identifier} = '${file.webPath}';",
        );
      }

      // Nested subdirectories.
      for (final child in dir.dirs) {
        final childClassName = _className(className, child.name);
        buffer.writeln();
        buffer.writeln(
          '  final $childClassName ${child.identifier} = const $childClassName();',
        );
      }

      buffer.writeln('}');
      buffer.writeln();
    }
  }

  // ---------------------------------------------------------------------------
  // Naming helpers
  // ---------------------------------------------------------------------------

  /// Build a private class name from a parent class name and a directory name.
  ///
  /// Example: `_className('Assets', 'logo')` → `_AssetsLogo`.
  /// Example: `_className('_AssetsLogo', 'icons')` → `_AssetsLogoIcons`.
  static String _className(String parent, String dirName) {
    final pascal = _toPascalCase(dirName);
    if (parent == 'Assets') return '_Assets$pascal';
    // parent is already prefixed with `_Assets`.
    return '$parent$pascal';
  }

  /// Convert a directory name to PascalCase.
  ///
  /// `my-icons` → `MyIcons`, `01-guides` → `$01Guides`.
  static String _toPascalCase(String name) {
    // Split on non-alphanumeric characters.
    final parts = name
        .split(RegExp(r'[^a-zA-Z0-9]'))
        .where((s) => s.isNotEmpty);
    final result = parts.map((s) => s[0].toUpperCase() + s.substring(1)).join();
    if (result.isEmpty) return 'Unnamed';
    // Leading digit — prefix with `$`.
    if (RegExp(r'^[0-9]').hasMatch(result)) return '\$$result';
    return result;
  }

  /// Convert a filename to a valid Dart snake_case identifier.
  ///
  /// `logo.webp` → `logo_webp`, `favicon-32x32.png` → `favicon_32x32_png`,
  /// `1icon.svg` → `$1icon_svg`.
  static String _toIdentifier(String name) {
    // Replace non-alphanumeric characters with underscores.
    var result = name.replaceAll(RegExp(r'[^a-zA-Z0-9_]'), '_');
    // Collapse consecutive underscores.
    result = result.replaceAll(RegExp(r'_+'), '_');
    // Strip leading/trailing underscores.
    result = result.replaceAll(RegExp(r'^_+|_+$'), '');
    if (result.isEmpty) return 'unnamed';
    // Leading digit — prefix with `$`.
    if (RegExp(r'^[0-9]').hasMatch(result)) return '\$$result';
    return result;
  }

  // ---------------------------------------------------------------------------
  // Empty fallback
  // ---------------------------------------------------------------------------

  static String _emptyAssets() {
    return '''
// AUTO-GENERATED by DocuDart from the assets/ directory.
// This file is regenerated on every build. Do not edit.

// ignore_for_file: non_constant_identifier_names

/// Type-safe asset paths generated from the `assets/` directory.
///
/// The assets directory is empty. Add files to `assets/` and rebuild.
abstract class Assets {
  Assets._();
}
''';
  }
}

// ---------------------------------------------------------------------------
// Internal tree representation (not exported)
// ---------------------------------------------------------------------------

class _AssetDir {
  const _AssetDir({
    required this.name,
    required this.identifier,
    required this.webPath,
    required this.dirs,
    required this.files,
  });
  final String name;
  final String identifier;
  final String webPath;
  final List<_AssetDir> dirs;
  final List<_AssetFile> files;
}

class _AssetFile {
  const _AssetFile({
    required this.name,
    required this.identifier,
    required this.webPath,
  });
  final String name;
  final String identifier;
  final String webPath;
}
