name: example_project
description: An example Dart project to demonstrate DocuDart documentation generator.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dev_dependencies:
  test: ^1.24.0
