// AUTO-GENERATED by DocuDart from the assets/ directory.
// This file is regenerated on every build. Do not edit.

// ignore_for_file: non_constant_identifier_names

/// Type-safe asset paths generated from the `assets/` directory.
///
/// Usage:
/// ```dart
/// img(src: Assets.logo.logo_webp, alt: 'Logo')
/// ```
abstract class Assets {
  Assets._();

  static const favicon = _AssetsFavicon();

  static const logo = _AssetsLogo();
}

/// Asset paths for `assets/favicon/`.
class _AssetsFavicon {
  const _AssetsFavicon();

  /// `/assets/favicon/android-chrome-192x192.png`
  final String android_chrome_192x192_png = '/assets/favicon/android-chrome-192x192.png';

  /// `/assets/favicon/android-chrome-512x512.png`
  final String android_chrome_512x512_png = '/assets/favicon/android-chrome-512x512.png';

  /// `/assets/favicon/apple-touch-icon.png`
  final String apple_touch_icon_png = '/assets/favicon/apple-touch-icon.png';

  /// `/assets/favicon/favicon-16x16.png`
  final String favicon_16x16_png = '/assets/favicon/favicon-16x16.png';

  /// `/assets/favicon/favicon-32x32.png`
  final String favicon_32x32_png = '/assets/favicon/favicon-32x32.png';

  /// `/assets/favicon/favicon.ico`
  final String favicon_ico = '/assets/favicon/favicon.ico';
}

/// Asset paths for `assets/logo/`.
class _AssetsLogo {
  const _AssetsLogo();

  /// `/assets/logo/logo.webp`
  final String logo_webp = '/assets/logo/logo.webp';
}

